#!/data/data/com.termux/files/usr/bin/bash

# Make sure you call this script with the command: source

lastvalue="ff44ee"
username="null"

function pubspeak() {
  if [ "$username" = "null" ];
  then
    read -p "Please enter a username: " username
    echo "Thank you for your cooperation"

  elif [ "$1" = "-help" ];
  then
    cat << delim
    Welcome to Pubspeak!
    With this script you can broadcast messages to your entire terminal
    Here are some extra commands:
    -txt   ; Sends the text file contents as a message
    -tedit ; Opens a temporary nano file to send a message
    -help  ; Displays this message
    -reset ; Resets the client
delim
    # End of help

  elif [ "$1" = "-txt" ];
  then
    echo "$username"": " > ~/.etc/.pubspeak
    cat "$2" >> ~/.etc/.pubspeak

  elif [ "$1" = "-tedit" ];
  then
    rm ~/.tmp
    nano ~/.tmp
    read -p "Done editing?  (y/n): " x
    if [ "$x" = "y" ];
    then
      echo "$username"": " > ~/.etc/.pubspeak
      cat ~/.tmp >> ~/.etc/.pubspeak
    else
      echo "Ok then restart"
    fi

  elif [ "$1" = "-reset" ];
  then
    read -p "Exit the session? (Y/n): " x
    if [ "$x" = "Y" ];
    then
      exit
    else
      echo "Ok then"
    fi

  else
    message="$username"": ""$1"
    echo "$message" > ~/.etc/.pubspeak
  fi
}


function _pubspeak_client() {
  while :
  do

    value=$(md5sum < ~/.etc/.pubspeak)
    if [ "$value" = "$lastvalue" ];
    then
      sleep 2
    else
      echo
      echo "--------STATE SPONSORED MESSAGE--------"
      echo
      cat ~/.etc/.pubspeak
      echo
      echo "--------STATE SPONSORED MESSAGE--------"
      lastvalue="$value"
    fi

  done
}

_pubspeak_client &
